services:
  # MySQL Database Service
  db:
    image: mysql:8.0
    container_name: todo_mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: todo_app_db
      MYSQL_USER: todo_user
      MYSQL_PASSWORD: todo_password
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./backend/database/migrations:/docker-entrypoint-initdb.d:ro
    networks:
      - todo_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    restart: unless-stopped

  # Laravel Backend Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: todo_backend_app
    working_dir: /var/www/html
    environment:
      APP_NAME: TodoApp
      APP_ENV: local
      APP_KEY: base64:nPjlM4ZpN5VqR6SxYzA9BcDeFgHiJkLmNoPqRsT+UvW=
      APP_DEBUG: "true"
      APP_URL: http://localhost:9000
      LOG_CHANNEL: single
      LOG_LEVEL: debug
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: todo_app_db
      DB_USERNAME: todo_user
      DB_PASSWORD: todo_password
      BROADCAST_DRIVER: log
      CACHE_DRIVER: file
      FILESYSTEM_DISK: local
      QUEUE_CONNECTION: sync
      SESSION_DRIVER: file
      SESSION_LIFETIME: 120
    volumes:
      - ./backend:/var/www/html
      - /var/www/html/vendor
      - /var/www/html/node_modules
    ports:
      - "9000:9000"
    networks:
      - todo_network
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  # React Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: todo_frontend_app
    ports:
      - "3000:80"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    networks:
      - todo_network
    depends_on:
      - backend
    restart: unless-stopped
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:9000/api

volumes:
  dbdata:
    driver: local

networks:
  todo_network:
    driver: bridge
